### ISSUE TITLE
Tennessee Public Employee Salaries

### ISSUE THREAD

**Issue by soodoku** [public-salaries/public_salaries#12]
URL = https://apps.tn.gov/salary/

When you click search, it gives a list of about 41k employees. pretty straightforward scraping job.

You can iterate deterministically via the URL: 
https://apps.tn.gov/salary-app/results?d-16544-p=2067
https://apps.tn.gov/salary-app/results?d-16544-p=2068

etc.

**Comment by ChrisMuir** [comment]
@soodoku The [tn README](https://github.com/public-salaries/public_salaries/blob/master/tn/readme.md) contains two dead links, one to a py scraper file and one to a 7z data file. I assume those files got lost during the repo transition?

**Comment by soodoku** [comment]
Nope. This is just a placeholder readme. I find it useful to write a readme for myself first. I am in the process of writing the script and producing the data. Nearly done actually.

**Comment by ChrisMuir** [comment]
Ahh, gotcha that makes sense. Good to know, thanks!
